/*
 * This source file was generated by the Gradle 'init' task
 */
package com.payment;

public class Main {
    public static void main(String[] args) {
        System.out.println("Payment Processing Simulator");
    }
}